### ISSUE TITLE
app.models.Process.DoesNotExist: Process matching query does not exist

### ISSUE THREAD

**Issue by alenweiru** [MateLabs/AutoOut#1]
when I upload the file and click the Detection button no thing happened but show the error below 
![image](https://user-images.githubusercontent.com/21155566/64136506-970f0800-ce24-11e9-9843-7744124b6bf7.png)

**Comment by kailashahirwar** [comment]
Before you start your server, execute these two commands
```
python manage.py loaddata app/fixtures/process_statuses.json
python manage.py loaddata app/fixtures/processes.json
```
